### ISSUE TITLE
Image name duplication

### ISSUE THREAD

**Issue by arusakov** [2ik/django-editorjs-fields#11]
When use default settings every uploaded image have the same name.

`IMAGE_NAME` is generated one time in `django_editorjs_fields/config.py`:

```
IMAGE_NAME = getattr(
    settings, "EDITORJS_IMAGE_NAME", token_urlsafe(8))
```

I think, that IMAGE_NAME (or something else) must be a callable object. So name can be different at every time.

**Comment by 2ik** [comment]
Hi, fixed in 0.2.2
