### ISSUE TITLE
EditorJsJSONField is not supported by modeltranslation

### ISSUE THREAD

**Issue by NightSommelier** [2ik/django-editorjs-fields#13]
> django.core.exceptions.ImproperlyConfigured: EditorJsJSONField is not supported by modeltranslation.

Что делать?

**Comment by 2ik** [comment]
Если используете пакет **django-modeltranslation**, то добавьте в настройках
`MODELTRANSLATION_CUSTOM_FIELDS = ("EditorJsJSONField",) `
[см.тут подробно](https://django-modeltranslation.readthedocs.io/en/latest/installation.html?highlight=MODELTRANSLATION_CUSTOM_FIELDS#modeltranslation-custom-fields)

Если не помогло то для начала уточните детали:
- версия django
- версия плагина
- пример кода, где используется EditorJsJSONField
- предоставьте полностью свою ошибку с путями к файлам
- список установленных пакетов помимо текущего плагина

**Comment by 2ik** [comment]
@NightSommelier еще актуально?

**Comment by NightSommelier** [comment]
> @NightSommelier еще актуально?

Спасибо за ответ. Не проверял, но думаю проверю в ближайшее время. Пока предпринял другое решение.
