### ISSUE TITLE
EditorJS configurable params

### ISSUE THREAD

**Issue by solace** [2ik/django-editorjs-fields#2]
Hello,

Thanks for this plugin. :)

Is there any chance of making [the other configurable options](https://github.com/codex-team/editor.js/blob/master/types/configs/editor-config.d.ts) for EditorJS able to be set through widget config?

In particular, I just need to disable autofocus, but the rest would be more flexible.

I know I can override the js, but it would be nice if it was a configurable thing.

Thanks!

**Comment by 2ik** [comment]
OK. I think it will be useful for others as well :) 
I will try to do it in the next 1-2 weeks

**Comment by solace** [comment]
That's amazing. Thanks. :)

**Comment by dfrankow** [comment]
I also need to disable autofocus.

**Comment by 2ik** [comment]
autofocus and other settings are already made. Release coming soon ;)

**Comment by 2ik** [comment]
added in 0.2.1
check the documentation ;)
