### ISSUE TITLE
TemplateDoesNotExist Error

### ISSUE THREAD

**Issue by ronejercito** [2ik/django-editorjs-fields#31]
Hi. I like your implementation of Editorjs for Django. For the most part, it works until I try to go to the admin. Strangely, I can go to the admin of one of my models with this package but not in the other. 

![image](https://user-images.githubusercontent.com/24636021/160259646-5fa97d8e-22ef-4aa0-859d-f798991b9490.png)

**Comment by 2ik** [comment]
Hi! I just tested, it works on django versions 3 and 4 perfectly. 
I don't understand where the file comes from editorjs.html?

**Comment by 2ik** [comment]
@ronejercito issue resolved?
