### ISSUE TITLE
The editor.js is not initiated when used inside of inlines

### ISSUE THREAD

**Issue by archatas** [2ik/django-editorjs-fields#32]
This problem occurs in Django administration and in frontend forms with dynamically addable inlines.

**Comment by archatas** [comment]
Ideally there could be a custom event to trigger that would reinitiate all widgets that haven't been initiated. Probably where you can pass the container element where to look for the textareas.

Also there should be multiple textareas allowed with the dynamically added formsets.

**Comment by 2ik** [comment]
can you give an example?

plugin in inlines are working in the admin panel, you can see [example](https://github.com/2ik/django-editorjs-fields/tree/dev/example)

**Comment by archatas** [comment]
If the admin inline has more than one Editor.js fields, only the first one gets initiated, and others are ignored and show textareas with the value "null".

You can see the problem from this [line of code](https://github.com/2ik/django-editorjs-fields/blob/dev/django_editorjs_fields/static/django-editorjs-fields/js/django-editorjs-fields.js#L166), when only the 0th textarea is initiated.

For inlines in the frontend, there is no way to trigger re-initiation, because the initation function initEditorJsField() is within a JavaScript closure – so no access to it at all.
