### ISSUE TITLE
'editorjs_image_upload' is not a valid view function or pattern name

### ISSUE THREAD

**Issue by breisfeld** [2ik/django-editorjs-fields#33]
Hi, 
I am a newcomer to Django.

I have installed `django-editorjs-fields` and added a `EditorJsTextField()` to a couple of my models. 
I have not included any plugins. 

When trying to add an instance of a model through the admin interface, I am getting the following exception:

```
Exception Type: NoReverseMatch
Reverse for 'editorjs_image_upload' not found. 'editorjs_image_upload' is not a valid view function or pattern name.
```

I have included  `django_editorjs_fields` in the `INSTALLED_APPS`. 

I am using `django v4.04` and `django-editorjs-fields v0.2.6`.

Thank you for your help.

**Comment by 2ik** [comment]
https://github.com/2ik/django-editorjs-fields#image-uploads

```python
# urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    ...
    path('editorjs/', include('django_editorjs_fields.urls')),
    ...
]
```

**Comment by 2ik** [comment]
can you upload your project to github? if not, please see an [example](https://github.com/2ik/django-editorjs-fields/tree/dev/example) 
at the moment I can't say exactly what the error is

**Comment by breisfeld** [comment]
Thank you for the reply. I found my error: I had neglected to include a `{{ form.media }}` variable in my html template.

**Comment by 2ik** [comment]
I am very glad that everything worked out for you!
