### ISSUE TITLE
How to beautify editor js while using in html template

### ISSUE THREAD

**Issue by NurulloSalaydinov** [2ik/django-editorjs-fields#34]

**Comment by 2ik** [comment]
just like everything else, via css..

**Comment by NurulloSalaydinov** [comment]
no, I created table ul li and others but it doesn't show the table and ul li correctly

**Comment by NurulloSalaydinov** [comment]
is there any styles for editor js or should i write it by myself

**Comment by 2ik** [comment]
use your own styles
