### ISSUE TITLE
как использовать на чтение? 

### ISSUE THREAD

**Issue by t0kie** [2ik/django-editorjs-fields#35]
Привет, подскажите пожалуйста как использовать его на чтение, чтобы то что я создал корректно отображалось после? 
post_view.html не работает в example.

**Comment by 2ik** [comment]
Пример должен работать, 
{% load editorjs %} подключен?

**Comment by t0kie** [comment]
Да, конечно, все подключено, но не работает.

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

{% load editorjs %}
{{ post.body_editorjs | editorjs}}
{{ post.body_custom | editorjs}}
{{ post.body_textfield | editorjs}}
</body>

</html>`

при редактировании - все супер.
при чтении инфы. 
https://imgur.com/a/aS1nicz

**Comment by 2ik** [comment]
по скринам все ок, так и должно работать. Если не хватает стилей их можно дописывать в своем шаблоне

**Comment by t0kie** [comment]
возможно вопросы супер глупые, но где мне найти список всех стилей?

**Comment by t0kie** [comment]
[https://imgur.com/a/yc6rvi8](url)

Возможно вы меня не поняли, когда я в админке создаю пост, все выглядит отлично.
Когда я читаю данные пост, все выглядит не так, совсем. 

`{% load editorjs %}
{% for p in post %}
    {{ p.body_editorjs | editorjs}}
{% endfor %}`

Читаю вот так, разве не должно оно выглядеть так, как в форме создания?

**Comment by t0kie** [comment]
Когда я прописал вручную судя по .css , все заработало.

но почему сам editorjs, когда я пытаюсь читать , то что ввел в админке, создает мне совсем другой стиль, нерабочий и при этом вовсе не относится к Warning.

https://i.imgur.com/5ICPAqF.png

сверху - я сам создал, после чтения стилей которые использует editorjs для создания Warning.
снизу автоматическое создание, с помощью {{ text | editrojs }}

результат:
https://imgur.com/a/mWYSLyk

**Comment by t0kie** [comment]
В итоге выходит что-то такое:

https://imgur.com/a/ovxSm5Q

**Comment by 2ik** [comment]
Так и должно быть. Я не делал стилизацию компонентов на фронте, т.к. у каждого проекта индивидуальный дизайн. Единственное, я только прописал теги html, чтобы удобно можно было стилизовать
