### ISSUE TITLE
How to solve this problem, checklist and urls are not showing

### ISSUE THREAD

**Issue by NurulloSalaydinov** [2ik/django-editorjs-fields#36]

**Comment by 2ik** [comment]
This is an open source project, you can send PR if you need that.

**Comment by NurulloSalaydinov** [comment]
i added checklist but it doesn't add it to field

**Comment by 2ik** [comment]
because they are not generated in html https://github.com/2ik/django-editorjs-fields/blob/dev/django_editorjs_fields/templatetags/editorjs.py
use your view to display correctly
