### ISSUE TITLE
Invalid config in EDITORJS_DEFAULT_CONFIG_TOOLS

### ISSUE THREAD

**Issue by aq1** [2ik/django-editorjs-fields#39]
I am not 100% sure but it seems that you need to keep keys in this dict `EDITORJS_DEFAULT_CONFIG_TOOLS` lowercase.
For example: `'list': {'class': 'List', 'inlineToolbar': True},`

If you keep them capitalized the data generated by the widget won't be valid outside admin widget, because EditorJs expects lowercased types of blocks. You can check it in plugins documentation or on main page of editor. For example 👇

<img width="641" alt="image" src="https://user-images.githubusercontent.com/3045638/181018257-846ab30d-1795-40e1-ab82-1e0a1cee2c69.png">

**Comment by 2ik** [comment]
if we do this, then after updating the plugin, app may have problems.
developers can use their own logic for displaying fields on front.
EDITORJS_DEFAULT_CONFIG_TOOLS parameter can always be customized in your settings
