### ISSUE TITLE
Displaying with Django Templates

### ISSUE THREAD

**Issue by gurugeek** [2ik/django-editorjs-fields#4]
First: thanks a lot for this package 👍 
interesting approach and also file upload works fine in admin. All is rendered properly in admin but I can't figure out how to render on a django template.
I tried this tutorial https://medium.com/analytics-vidhya/integrating-editorjs-with-django-7a30127d0771 but I receive some js errors .

Since you have an example may be you can add a template to your example for rendering ? 
Thank you!

**Comment by 2ik** [comment]
Hello,
here's a [similar question](https://github.com/2ik/django-editorjs-fields/issues/1). I tried to describe in detail)) 
But also I'm going to create custom filters on a django template.

**Comment by dannluciano** [comment]
Me too.

**Comment by 2ik** [comment]
added in 0.2.1
