### ISSUE TITLE
Login Required for /editorjs/image_upload/

### ISSUE THREAD

**Issue by sanyam1992000** [2ik/django-editorjs-fields#5]
While posting image with /editorjs/image_upload/ it redirects to login page first

**Comment by egor83** [comment]
I have run into the same problem - do you by chance remember what the solution was?

**Comment by egor83** [comment]
Turns out django-editorjs-fields requires the user to be `is_staff` for image uploads to work:
https://github.com/2ik/django-editorjs-fields/blob/d744fef133b38091092261eacaf2fe2369044210/django_editorjs_fields/urls.py#L9
