### ISSUE TITLE
Delete ,moveDown ,Moveup not showing on  onclick for image plugin

### ISSUE THREAD

**Issue by sherrywilly** [2ik/django-editorjs-fields#59]
![image](https://user-images.githubusercontent.com/40135571/235166442-4ff303e2-c372-4f07-b29e-f790c237996e.png)
Delete ,moveDown ,Moveup not showing on  onclick for image plugin

**Comment by sherrywilly** [comment]
![image](https://user-images.githubusercontent.com/40135571/235167687-938e9d44-0ac0-458f-8474-a78e08721b2b.png)

**Comment by sherrywilly** [comment]
same issue with Heading also

**Comment by rrseone** [comment]
Any solution for this problem?

**Comment by sergio-itru** [comment]
in your settings.py file try to add variable like this: EDITORJS_VERSION = '2.27.0'

**Comment by sherrywilly** [comment]
Thanks @sergio-itru it worked for me
