### ISSUE TITLE
Some field tuning problem with django admin

### ISSUE THREAD

**Issue by rrseone** [2ik/django-editorjs-fields#64]
![Screenshot from 2023-10-05 13-41-59](https://github.com/2ik/django-editorjs-fields/assets/32605840/225dabda-dd57-4884-8b8e-8cce99ac899c)

![Screenshot from 2023-10-05 13-45-06](https://github.com/2ik/django-editorjs-fields/assets/32605840/240fcaae-b08c-431a-919a-fff09a463dca)

Not showing close button

**Comment by rashidone** [comment]
![Screenshot from 2023-10-05 13-45-06](https://github.com/2ik/django-editorjs-fields/assets/32605840/ee53c80f-e32b-41e2-bf23-17ceae8be413)

Also not working with list
