### ISSUE TITLE
Есть ли какая-нибудь возможность создавать формы в темплейтах?

### ISSUE THREAD

**Issue by Obre4en** [2ik/django-editorjs-fields#7]
Есть ли какая-нибудь возможность создавать формы в темплейтах?

**Comment by hacktivision** [comment]
Есть [похожий плагин](https://pypi.org/project/django-editorjs/), с это реализацией не работал, но думаю что возможно.

**Comment by 2ik** [comment]
Добавлено в 0.2.1
[См. пример](https://github.com/2ik/django-editorjs-fields/blob/main/example/blog/forms.py)
