### ISSUE TITLE
How to show the content of body in detail view, its showing json format

### ISSUE THREAD

**Issue by Sourmundada** [2ik/django-editorjs-fields#8]

**Comment by nolepeople** [comment]
.

**Comment by 2ik** [comment]
Use [custom filters](https://docs.djangoproject.com/en/3.1/howto/custom-template-tags/#writing-custom-template-filters). Example: https://github.com/2ik/django-editorjs-fields/issues/1

This will be available in the update

**Comment by Oliv6176** [comment]
@2ik Is the update in the works? or is there anything I can help with?

**Comment by 2ik** [comment]
> @2ik Is the update in the works? or is there anything I can help with?

I'm working on a plugin, but time is the enemy)

**Comment by martincpt** [comment]
Any update on this?

**Comment by 2ik** [comment]
Added in 0.2.1
