### ISSUE TITLE
How to use with ModelForm?

### ISSUE THREAD

**Issue by dadokkio** [2ik/django-editorjs-fields#9]
Hello,
I was able to use the plugin in template with templatetags and admin, but I'm not able to use it in ModelForm.
I tried both using the EditorJsFieldMixin that specifying field or widget but nothing happens.

**Comment by 2ik** [comment]
added in 0.2.1
[See example](https://github.com/2ik/django-editorjs-fields/blob/main/example/blog/forms.py)
